name: Alluxio Controller Docker Image CI

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Alibaba Cloud ACR
      uses: docker/login-action@v1
      with:
        registry: <your-acr-registry-url>
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}

    - name: Build and Push Docker Image
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./fluid/docker/Dockerfile
        push: true
        tags: <your-acr-registry-url>/<your-repo-name>/my-image:latest

    - name: Logout from ACR
      run: docker logout <your-acr-registry-url>
