name: Alluxio Controller Docker Image CI

env:
  HELM_VERSION: helm-v3.11.3
  TARGETARCH: amd64

on:
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Aliyun Container Registry (ACR)
      uses: aliyun/acr-login@v1
      with:
        login-server: https://registry.cn-hangzhou.aliyuncs.com

        username: "${{ secrets.ACR_USERNAME }}"
        password: "${{ secrets.ACR_PASSWORD }}"


    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./docker/Dockerfile.alluxioruntime
        push: true
        tags: registry.cn-hangzhou.aliyuncs.com/wwdldg/fluid:latest
        build-args: |
          HELM_VERSION=${{ env.HELM_VERSION }}
          TARGETARCH=${{ env.TARGETARCH }}

    - name: Logout from ACR
      run: docker logout registry.cn-hangzhou.aliyuncs.com
